config/routes.rb
Rails.application.routes.draw do

  root 'general_pages#index'

  get 'about-us', to: 'general_pages#about_us', as: :about_us
  get 'contact-us', to: 'general_pages#contact_us', as: :contact_us
  get 'terms-of-service', to: 'general_pages#terms_of_service', as: :terms_of_service
  get 'faq', to: 'general_pages#faq', as: :faq

  devise_for :admins, path: 'admins', controllers: {
    sessions: "admins/sessions",
    confirmations: "admins/sessions",
    passwords: "admins/passwords",
    registrations: "admins/registrations",
    unlocks: "admins/unlocks"
  }

  devise_for :brokers, path: 'brokers', controllers: {
    sessions: "brokers/sessions",
    confirmations: "brokers/sessions",
    passwords: "brokers/passwords",
    registrations: "brokers/registrations",
    unlocks: "brokers/unlocks"
  }

  devise_for :agents, path: 'agents', controllers: {
    sessions: "agents/sessions",
    confirmations: "agents/sessions",
    passwords: "agents/passwords",
    registrations: "agents/registrations",
    unlocks: "agents/unlocks"
  }

  devise_for :owners, path: 'owners', controllers: {
    sessions: "owners/sessions",
    confirmations: "owners/sessions",
    passwords: "owners/passwords",
    registrations: "owners/registrations",
    unlocks: "owners/unlocks"
  }

  devise_for :prospects, path: 'users', controllers: {
    sessions: "prospects/sessions",
    confirmations: "prospects/sessions",
    # omniauth_callbacks: "prospects/omniauth_callbacks",
    passwords: "prospects/passwords",
    registrations: "prospects/registrations",
    unlocks: "prospects/unlocks"
  }

end

app/views/shared/_main_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Lease Simple</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'About Us', about_us_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          More ...
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'FAQ', faq_path, class: "dropdown-item" %>
          <%= link_to 'Terms of Service', terms_of_service_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to 'Contact Us', contact_us_path, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
    <% if current_owner %>
      <%= link_to 'Sign Out', destroy_owner_session_path, method: :delete, class: "btn btn-danger navbar-button" %>
    <% elsif current_prospect %>
      <%= link_to 'Sign Out', destroy_prospect_session_path, method: :delete, class: "btn btn-danger navbar-button" %>
    <% else %>
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle btn btn-secondary navbar-button" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sign In As ...
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Owner', owner_session_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to 'Prospect', prospect_session_path, class: "dropdown-item" %>
        </div>
      </div>
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle btn btn-outline-primary navbar-button" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sign Up As ...
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Owner', new_owner_registration_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to 'Prospect', new_prospect_registration_path, class: "dropdown-item" %>
        </div>
      </div>
    <% end %>
    <%
=begin%>
 <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> 
<%
=end
%>
  </div>
</nav>